#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

source "${script_dir}/configuration"

echo 'Running'
echo 'Running with java'
echo 'Running c extension (java)'
java -jar "${use_jar_path}"
echo

java -D${jni_native_name_hyphenated}.debug-build="true" -jar "${use_jar_path}"
echo

echo 'Running rust extension (java)'
java -D${jni_native_name_hyphenated}.rust="true" -jar "${use_jar_path}"
echo

java -D${jni_native_name_hyphenated}.debug-build="true" \
  -D${jni_native_name_hyphenated}.rust="true" \
  -jar "${use_jar_path}"
echo

"${root_directory}/local_run"

echo 'Done running'

