#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

source "${script_dir}/configuration"

jar tvf "${jar_path}"

echo
echo 'META-INF/MANIFEST.MF content:'
unzip -p "${jar_path}" META-INF/MANIFEST.MF
